# Generated by Django 2.2 on 2021-01-22 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tps', '0005_tienda_visitas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archived', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('imagen', models.FileField(upload_to='images')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='tienda',
            name='imagen',
            field=models.FileField(default=None, upload_to='images'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tienda',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='elemento',
            name='imagenes',
            field=models.ManyToManyField(blank=True, to='tps.Imagen'),
        ),
    ]
