# Generated by Django 2.2 on 2021-02-22 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tps', '0006_auto_20210122_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tienda',
            name='imagen',
            field=models.FileField(blank=True, null=True, upload_to='images'),
        ),
    ]
