# Generated by Django 2.2 on 2021-04-20 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tps', '0007_auto_20210222_0201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tienda',
            name='elementos',
        ),
    ]
